import os
import json
import re

base_path = r'C:\Users\ASUS\.gemini\antigravity\brain\ce690af0-b223-4010-9f63-e53ea489fb91\.system_generated\steps'

def extract(p):
    full_path = os.path.join(base_path, p)
    print("Reading", full_path)
    if not os.path.exists(full_path):
        return []
        
    with open(full_path, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()
        
    # The payload MUST contain [{"jsonb_agg": ... }]
    # We regex exactly that part
    # Look for literally the array notation
    # In python, we can just find where jsonb_agg begins
    idx = content.find('"jsonb_agg"')
    if idx == -1:
        print("No jsonb_agg string found in file")
        return []
        
    # go backwards to find the `[`
    start_idx = content.rfind('[', 0, idx)
    # go forwards to find the `]` which closes the array. 
    # But wait, it's inside a string representation. So it's actually literal `[` inside a JSON string.
    # We can just unescape the entire content if it's a valid JSON string
    obj = None
    try:
        obj = json.loads(content)
    except: pass
    
    if obj and "result" in obj:
        text = obj["result"]
    else:
        text = content
        
    match = re.search(r'(\[\s*\{\s*"jsonb_agg"[\s\S]*?\}\s*\])', text)
    if match:
        arr_str = match.group(1)
        try:
            parsed = json.loads(arr_str)
            if 'jsonb_agg' in parsed[0] and parsed[0]['jsonb_agg']:
                print(f"Extracted {len(parsed[0]['jsonb_agg'])} items")
                return parsed[0]['jsonb_agg']
        except Exception as e:
            print("Failed to parsed array string:", e)
            print("Array str started with:", arr_str[:50])
    
    return []

paths = ['158/output.txt', '159/output.txt', '160/output.txt', '161/output.txt']
tq_paths = ['166/output.txt', '167/output.txt', '168/output.txt']

all_questions = []
for p in paths:
    all_questions.extend(extract(p))

all_tq = []
for p in tq_paths:
    all_tq.extend(extract(p))

def escape_sql(val):
    if val is None:
        return 'NULL'
    if isinstance(val, str):
        return "'" + val.replace("'", "''") + "'"
    if isinstance(val, (dict, list)):
        return "'" + json.dumps(val).replace("'", "''") + "'"
    return str(val)

sql = "-- Migration script generated by script\nBEGIN;\n\n"
for q in all_questions:
    sql += f"INSERT INTO public.questions (id, subject_id, type, difficulty, content, options, correct_answer, explanation) VALUES ({escape_sql(q.get('id'))}, {q.get('subject_id')}, {escape_sql(q.get('type'))}, {escape_sql(q.get('difficulty'))}, {escape_sql(q.get('content'))}, {escape_sql(q.get('options'))}::jsonb, {escape_sql(q.get('correct_answer'))}::jsonb, {escape_sql(q.get('explanation'))}) ON CONFLICT (id) DO NOTHING;\n"

tryout = [{"id":"7910cfb9-9baa-4ce3-8316-e7ff4c7ca166","title":"Tryout UTBK SNBT Nasional Vol. 1","is_active":True,"created_at":"2026-04-02T15:43:01.319528+00:00","description":"Uji coba resmi berskala nasional SNBT dengan sistem IRT (Item Response Theory). Terdiri dari 7 subtes 155 soal.","duration_minutes":195}]
for t in tryout:
    sql += f"INSERT INTO public.tryouts (id, title, description, duration_minutes, is_active, created_at) VALUES ({escape_sql(t['id'])}, {escape_sql(t['title'])}, {escape_sql(t['description'])}, {t['duration_minutes']}, {str(t['is_active']).lower()}, {escape_sql(t['created_at'])}) ON CONFLICT (id) DO NOTHING;\n"

sections = [{"id":"558b581e-feec-4ed2-aa3f-235c11d94466","tryout_id":"7910cfb9-9baa-4ce3-8316-e7ff4c7ca166","subject_id":1,"order_index":1,"duration_minutes":25},{"id":"2c6f7596-f15e-4db5-bded-8606a42b2748","tryout_id":"7910cfb9-9baa-4ce3-8316-e7ff4c7ca166","subject_id":2,"order_index":2,"duration_minutes":25},{"id":"caf8a14c-6dff-4c6d-b04d-be81c624a9b6","tryout_id":"7910cfb9-9baa-4ce3-8316-e7ff4c7ca166","subject_id":3,"order_index":3,"duration_minutes":25},{"id":"8556acd1-6d68-4bf1-b667-205933599cc6","tryout_id":"7910cfb9-9baa-4ce3-8316-e7ff4c7ca166","subject_id":4,"order_index":4,"duration_minutes":25},{"id":"03a1e70f-e18a-480b-90e7-53ba08a22268","tryout_id":"7910cfb9-9baa-4ce3-8316-e7ff4c7ca166","subject_id":5,"order_index":5,"duration_minutes":25},{"id":"f4320143-0fe4-4525-a146-dd43d2bdf7ff","tryout_id":"7910cfb9-9baa-4ce3-8316-e7ff4c7ca166","subject_id":6,"order_index":6,"duration_minutes":25},{"id":"e45a068c-8767-4523-95f9-27b64f8dcb6e","tryout_id":"7910cfb9-9baa-4ce3-8316-e7ff4c7ca166","subject_id":7,"order_index":7,"duration_minutes":25}]
for s in sections:
    sql += f"INSERT INTO public.tryout_sections (id, tryout_id, subject_id, order_index, duration_minutes) VALUES ({escape_sql(s['id'])}, {escape_sql(s['tryout_id'])}, {escape_sql(s['subject_id'])}, {escape_sql(s['order_index'])}, {escape_sql(s['duration_minutes'])}) ON CONFLICT (id) DO NOTHING;\n"

for tq in all_tq:
    sql += f"INSERT INTO public.tryout_questions (id, section_id, question_id, order_index) VALUES ({escape_sql(tq.get('id'))}, {escape_sql(tq.get('section_id'))}, {escape_sql(tq.get('question_id'))}, {escape_sql(tq.get('order_index'))}) ON CONFLICT (id) DO NOTHING;\n"

sql += "COMMIT;\n"
out_path = r'd:\Hackathon\LoginPTN\supabase\migrations\004_data_migration.sql'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(sql)
print(f"Generated {out_path} with {len(all_questions)} questions and {len(all_tq)} tryout links.")
